### ISSUE TITLE
Doesn't Retrieve All HTML Files in Folder, Throws Invalid Argument "*" Error

### ISSUE THREAD

**Issue by johnsonbui** [seffyroff/google-keep-to-evernote-converter#2]
Running the file on Windows with arguments below returns:

`python keep-to-enex.py /*.html -o convertedNotes.enex`
> Traceback (most recent call last):
> File "keep-to-enex.py", line 182, in <module>
>     mungefile(args.htmlSource[0])
>  File "keep-to-enex.py", line 64, in mungefile
>     fp = open(fn, 'r', encoding="utf8")
> OSError: [Errno 22] Invalid argument: '/*.html'

**Comment by johnsonbui** [comment]
Nvm, I was expecting the file to automatically pull all of the files from the directory and generate outputs, but this functionality isn't supported.
